### ISSUE TITLE
Quantum-Train LSTM Demo

### ISSUE THREAD

**Issue by Abeeekoala** [PennyLaneAI/qml#1175]
#### General information

**Name**
Chu-Hsuan Abraham Lin

**Affiliation** (optional)
Imperial College London

--------------------------------------------------------------------------------

#### Demo information

**Title**
Quantum-Train Long Short-Term Memory (QT-LSTM) for Wave Prediction (PennyLane Public Demo)

**Abstract**
This tutorial features the Quantum Train architecture proposed by Chen-Yu Liu et al. You can find more details on [arXiv:2405.11304](https://arxiv.org/abs/2405.11304) and [arXiv:2402.16465](https://arxiv.org/abs/2402.16465). Originally, in Deloitte’s Quantum Climate Challenge 2024, we implemented QT-LSTM to predict flood events along the Wupper River. However, due to the confidentiality of the data, we can only demonstrate QT-LSTM with fabricated data for simplicity while showcasing the power of this framework. In this tutorial, we implemented a classical LSTM model to learn the time-series wave data. We then explore the components of the LSTM model and finally implement the QT-LSTM.

**Relevant links**
[GitHub Repo](https://github.com/Abeeekoala/Quantum-Train-LSTM-PennyLane-Demo)

**Comment by CatalinaAlbornoz** [comment]
Hi @Abeeekoala , thank you for submitting this demo! 🙌 
We'll review it and get back to you in the next few days.

**Comment by ikurecic** [comment]
Hi @Abeeekoala , thanks so much for sharing the code from your project, and congrats again. ☺

There are a couple of things that might be nice to add, if you could take a quick look at them here:
- In the `torch.save(model_qt, 'model_/model_loss_bsf')` line it would be worth it to add a comment to note that it's a local folder.
- Could you make a comment in the repository readme or in the requirements file about the package versions you used to run the code? This would help with reproducibility.
- Can you confirm that the authors for this code project should be Chen-Yu Liu and yourself, like listed in the repository?
- It would be great if you could add the titles of the papers in the repository readme together with the arXiv links and designations that you already have.
- I've noticed a tiny typo, 'pakages' instead of 'packages' right at the start of the notebook.
- And, finally, would you want our Marketing Team to tag you on social media? ☺ If you share your (and/or Chen-Yu Liu's) LinkedIn and/or Twitter/X profiles, I will be able to forward those to them.

This looks great, I'm looking forward to sharing it!

**Comment by Abeeekoala** [comment]
Hi @ikurecic, thanks for the feedback we have updated the repository.
In response to your questions

- Yes, Chen-Yu Liu and I are the authors of this code project.
- Yes, we are happy to be tagged. Our LinkedIn profiles are [Chu-Hsuan Abraham Lin](www.linkedin.com/in/chu-hsuan-abraham-lin) and [Chen-Yu Liu](https://www.linkedin.com/in/chen-yu-liu-549289194/)

Thanks again for your invitation to this demo and we look forward to hearing from you soon.

**Comment by ikurecic** [comment]
Hi @Abeeekoala , that's brilliant, thanks so much! ☺
It should be live [here](https://pennylane.ai/qml/demos_community/) either later today or on Monday, and our Marketing Team will tag you both on LinkedIn in the next couple of weeks.

Great job and congrats again on your hard work, this is really cool and I'm looking forward to seeing where you folks go next. :)

**Comment by Abeeekoala** [comment]
That is fantastic, thank you so much.

Ivana Kurečić ***@***.***> 於 2024年8月3日 週六 上午12:26寫道：
