### ISSUE TITLE
qCBR

### ISSUE THREAD

**Issue by pifparfait** [PennyLaneAI/qml#410]
#### General information
A supervised classifier can be interpreted as a program capable of predicting the output of input from the labelled data. From the input data and the label, with known examples, we will be able to, which will be the label given new input.

The main idea of quantum Case-Based Reasoning (qCBR)1 is to interpret the statement of the problem as an input and the solution to the problem as an output. Therefore, if we have a series of situations with their outcomes, we can train our classifier to determine its solution given a new problem.

**Name**
Parfait Atchade

**Affiliation** (optional)
Your affiliation, if applicable; e.g. University, research institute, company.

**Twitter** (optional)
@pifparfait
Your Twitter username, if interested; helps us advertise your demo while linking directly back to you.

**Image** (optional)
https://github.com/pifparfait/qCBR/blob/master/qCBR_2.png

--------------------------------------------------------------------------------

#### Demo information

**Title**
qCBR-learning-by-cases

**Abstract**
A supervised classifier can be interpreted as a program capable of predicting the output of input from the labelled data. From the input data and the label, with known examples, we will be able to, which will be the label given new input. The main idea of quantum Case-Based Reasoning (qCBR) is to interpret the statement of the problem as an input and the solution to the problem as an output. Therefore, if we have a series of situations with their outcomes, we can train our classifier to determine its solution given a new problem.

**Relevant links**
https://github.com/pifparfait/qCBR-learning-by-cases
https://arxiv.org/abs/2104.00409

**Comment by CatalinaAlbornoz** [comment]
Hi @pifparfait, 
Your demo is amazing! Congratulations!

I have slightly modified the summary so that it's easier for others to understand. Below id the new version. What do you think?

A supervised classifier is a program that can predict a label (class) for a new input object, based on the value of its attributes and on a training set. The training set consists of labelled data. The main idea of quantum Case-Based Reasoning (qCBR) is to interpret the statement of the problem as an input object, and the solution to the problem as an output (label). Therefore, if we have a series of situations (inputs) with their outcomes (labels), we can train our classifier to determine the solution given a new problem.

**Comment by pifparfait** [comment]
Many thanks, Catalina! It looks perfect!

**Comment by CatalinaAlbornoz** [comment]
Awesome! I will let you know when it's up in the website.

**Comment by pifparfait** [comment]
Great @CatalinaAlborno! Many thanks

**Comment by CatalinaAlbornoz** [comment]
Hi @pifparfait, the demo is up on the [PennyLane website](https://pennylane.ai/qml/demos_community.html)! I'm not sure if we will get to promote it on Twitter next week but if not then we will promote it in January. Thank you and congratulations on this demo!

**Comment by pifparfait** [comment]
Many thanks To you, @CatalinaAlbornoz. Let us keep improving.
