### ISSUE TITLE
Updating reference format in existing pages

### ISSUE THREAD

**Issue by co9olguy** [PennyLaneAI/qml#53]
Currently we have a mixture of links to web media (e.g., wikipedia pages) and academic style citations (which appear in the docs as, e.g.,  `[R4]`). The academic citatation style does not fit well because:
- on any given page, only a subset of references are made, so the ordering can be disconcerting
- the actual style of the referencing does not fit well into the style of the rest of the text (e.g., when we have `see [R4]`, it would not be clear what `[R4]` is, but something like `see [Schuld & Killoran 2019]` would be more obvious. 
- clicking on a citation just takes you to a page of references, not to the desired reference itself

It would be good to decide a more natural and seamless way to cite academic works without breaking out of the overall style we are aiming for with these pages

**Comment by josh146** [comment]
It looks like sphinx-bibtex supports custom formatting: https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#custom-formatting-sorting-and-labelling

However, there is no built-in way to do this --- instead, a [custom pybtex plugin](https://docs.pybtex.org/api/plugins.html#pybtex-style-labels) has to be written.

Options include:

* Write a custom pybtex formatting/label style (cons: maintenance overhead, another thing that could break as dependencies change etc.)

* Have a per-page bibliography, rather than a separate page (like we do with the tutorials, although this could be combined with sphinx-bibtex).

* Drop sphinx-bibtex altogether, and just do manual hyperlinks (like we do in the tutorials).

I have a slight preference to dropping sphinx-bibtex altogether.

**Comment by co9olguy** [comment]
I vote for option 3 as well

**Comment by mariaschuld** [comment]
Voting for 3 too. I will implement it in the REDESIGN PR.

**Comment by mariaschuld** [comment]
Suggestion of the following convention: 

* We always cite arxiv papers, unless there is none (open source, more timely, easier to maintain)
* 3 or less authors are named as "Surname1, Surname2, Surname3 (YEAR)", more authors are named as "Surname1 et al. (YEAR)"
* The year is the year of the first arxiv identifier (if applicable)
* Hyperlinks are used like this: `Surname1 et al. (YEAR) <https://arxiv.org/abs/XXX.XXXXX>`_

**Comment by josh146** [comment]
I agree with all of the above @mariaschuld! In addition, I also quite like pages with bibliographies at the bottom, like https://pennylane.ai/qml/app/tutorial_data_reuploading_classifier.html#references. This could be an optional (but encouraged) section at the bottom of tutorials.

**Comment by josh146** [comment]
Since this issue was opened, we've coalesced onto the following per-page referencing strategy over in Strawberry Fields, using built-in ReST roles:

```rest
# This page looks at how to use GBS to construct a similarity measure between graphs,
# known as a graph kernel [[#schuld2019quantum]_]. Kernels can be applied to graph-based
# data for machine learning tasks such as classification using a support vector machine.
~~~~
#
# References
# ----------
#
# .. [#schuld2019quantum]
#
#     Maria Schuld, Kamil Brádler, Robert Israel, Daiqin Su, and Brajesh Gupt.
#     A quantum hardware-induced graph kernel based on gaussian boson sampling.
#     `arXiv preprint arXiv:1905.12646 <https://arxiv.org/abs/1905.12646>`__, 2019.
#
# .. [#bradler2018graph]
#
#     Kamil Bradler, Shmuel Friedland, Josh Izaac, Nathan Killoran, and Daiqin Su.
#     Graph isomorphism and Gaussian boson sampling.
#     `arXiv preprint arXiv:1810.10644 <https://arxiv.org/abs/1810.10644>`__, 2018.
```

The nice thing about use ReST footnotes is that

1. It is easy to find and reference required citations in the raw text file, and

2. Sphinx will automatically create in-page links between the citation and the References section at the bottom of the page, _in both directions._

E.g.:

![image](https://user-images.githubusercontent.com/2959003/81770461-7c4a7280-951f-11ea-84d3-6128272f11e8.png)

![image](https://user-images.githubusercontent.com/2959003/81770475-87050780-951f-11ea-86ce-cda18ec187f0.png)

**Comment by co9olguy** [comment]
What does the `1(1,2,3)` mean?

**Comment by josh146** [comment]
Easier to describe by linking to a live example:
https://710-214003948-gh.circle-artifacts.com/0/_build/html/demos/tutorial_rosalin.html#references

**Comment by glassnotes** [comment]
Closing this issue as all demos appear to have adopted one of the reference formats described above (inline citations, or bottom-of-the page bibliography). We can open a new issue for any further suggestions and/or updates to the references.
